### ISSUE TITLE
unknown actor creator [class akka.persistence.inmemory

### ISSUE THREAD

**Issue by hepin1989** [dnvriend/akka-persistence-inmemory#20]
with version `1.2.5`
```
[Error][2016-02-16 15:55:39]: unknown actor creator [class akka.persistence.inmemory.journal.InMemoryJournal]

akka.actor.ActorInitializationException: exception during creation
at akka.actor.ActorInitializationException$.apply(Actor.scala:172)
at akka.actor.ActorCell.create(ActorCell.scala:606)
at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
at akka.dispatch.Mailbox.run(Mailbox.scala:223)
at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: unknown actor creator [class akka.persistence.inmemory.journal.InMemoryJournal]
at akka.actor.IndirectActorProducer$.apply(IndirectActorProducer.scala:62)
at akka.actor.Props.producer(Props.scala:132)
at akka.actor.Props.<init>(Props.scala:145)
at akka.persistence.Persistence.akka$persistence$Persistence$$createPlugin(Persistence.scala:280)
at akka.persistence.Persistence$PluginHolderExtensionId.createExtension(Persistence.scala:300)
at akka.persistence.Persistence$PluginHolderExtensionId.createExtension(Persistence.scala:294)
at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:757)
at akka.actor.ExtensionId$class.apply(Extension.scala:79)
at akka.persistence.Persistence$PluginHolderExtensionId.apply(Persistence.scala:294)
at akka.persistence.Persistence.pluginHolderFor(Persistence.scala:258)
at akka.persistence.Persistence.journalConfigFor(Persistence.scala:214)
at akka.persistence.Eventsourced$class.$init$(Eventsourced.scala:55)
at qgame.engine.pay.module.order.UnHandledReceiptActor.<init>(UnHandledReceiptActor.scala:17)
at qgame.engine.pay.module.order.UnHandledReceiptActor$$anonfun$props$1.apply(UnHandledReceiptActor.scala:71)
at qgame.engine.pay.module.order.UnHandledReceiptActor$$anonfun$props$1.apply(UnHandledReceiptActor.scala:71)
at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
at akka.actor.Props.newActor(Props.scala:214)
at akka.actor.ActorCell.newActor(ActorCell.scala:562)
at akka.actor.ActorCell.create(ActorCell.scala:588)
... 9 more
```

**Comment by dnvriend** [comment]
Do you have akka.persistence.journal.plugin = "inmemory-journal" configured in your application.conf? You can take a look at the demo project at https://github.com/dnvriend/demo-akka-persistence-jdbc a fully configured demo project for akka persistence that uses the inmemory plugin and the jdbc plugin.
