### ISSUE TITLE
Fails with exception on start

### ISSUE THREAD

**Issue by stasimus** [dnvriend/akka-persistence-inmemory#26]
Akka version 2.11-2.4.6
library version 1.2.14

in application.conf I put:

akka ...
 actor ...
  persistence {
    journal.plugin = "inmemory-journal"
    snapshot-store.plugin = "inmemory-snapshot-store"
  }

Getting exception wich looks like incomatible to version

`[11:04:13][Step 1/1] app 2016-05-26 11:04:13.828 ERROR [coreservices-akka.actor.default-dispatcher-37][][akka.actor.OneForOneStrategy][][][][][] head of empty list
[11:04:13][Step 1/1] app java.util.NoSuchElementException: head of empty list
[11:04:13][Step 1/1] app 	at scala.collection.immutable.Nil$.head(List.scala:420) ~[scala-library-2.11.8.jar:na]
[11:04:13][Step 1/1] app 	at scala.collection.immutable.Nil$.head(List.scala:417) ~[scala-library-2.11.8.jar:na]
[11:04:13][Step 1/1] app 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) ~[akka-actor_2.11-2.4.6.jar:na]
[11:04:13][Step 1/1] app 	at akka.actor.ActorCell.invoke(ActorCell.scala:495) ~[akka-actor_2.11-2.4.6.jar:na]
[11:04:13][Step 1/1] app 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.11-2.4.6.jar:na]
[11:04:13][Step 1/1] app 	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.11-2.4.6.jar:na]
[11:04:13][Step 1/1] app 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_40]
[11:04:13][Step 1/1] app 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_40]
[11:04:13][Step 1/1] app 	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_40]
[11:04:13][Step 1/1] app 2016-05-26 11:04:13.836 ERROR [coreservices-akka.actor.default-dispatcher-37][][akka.actor.ActorSystemImpl][][][][][] Uncaught fatal error from thread [coreservices-akka.persistence.dispatchers.default-plugin-dispatcher-40] shutting down ActorSystem [coreservices]
[11:04:13][Step 1/1] app java.lang.NoSuchMethodError: akka.stream.ActorMaterializer$.apply(Lscala/Option;Lscala/Option;Lakka/actor/ActorRefFactory;)Lakka/stream/ActorMaterializer;
[11:04:13][Step 1/1] app 	at akka.persistence.inmemory.snapshot.InMemorySnapshotStore.<init>(InMemorySnapshotStore.scala:33) ~[akka-persistence-inmemory_2.11-1.2.14.jar:1.2.14]
[11:04:13][Step 1/1] app 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_40]
[11:04:13][Step 1/1] app 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_40]
[11:04:13][Step 1/1] app 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_40]
[11:04:13][Step 1/1] app 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_40]
[11:04:13][Step 1/1] app 	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_40]
[11:04:13][Step 1/1] app 	at akka.util.Reflect$.instantiate(Reflect.scala:44) ~[akka-actor_2.11-2.4.6.jar:na]
[11:04:13][Step 1/1] app 	at akka.actor.NoArgsReflectConstructor.produce(IndirectActorProducer.scala:105) ~[akka-actor_2.11-2.4.6.jar:na]
[11:04:13][Step 1/1] app 	at akka.actor.Props.newActor(Props.scala:213) ~[akka-actor_2.11-2.4.6.jar:na]
[11:04:13][Step 1/1] app 	at akka.actor.ActorCell.newActor(ActorCell.scala:562) ~[akka-actor_2.11-2.4.6.jar:na]
[11:04:13][Step 1/1] app 	at akka.actor.ActorCell.create(ActorCell.scala:588) ~[akka-actor_2.11-2.4.6.jar:na]
[11:04:13][Step 1/1] app 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461) ~[akka-actor_2.11-2.4.6.jar:na]
[11:04:13][Step 1/1] app 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483) ~[akka-actor_2.11-2.4.6.jar:na]
[11:04:13][Step 1/1] app 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282) ~[akka-actor_2.11-2.4.6.jar:na]
[11:04:13][Step 1/1] app 	at akka.dispatch.Mailbox.run(Mailbox.scala:223) ~[akka-actor_2.11-2.4.6.jar:na]
[11:04:13][Step 1/1] app 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_40]
[11:04:13][Step 1/1] app 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_40]
[11:04:13][Step 1/1] app 	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_40]`

**Comment by dnvriend** [comment]
Hi, please take a look at [a small demo for the akka-persistence-inmemory project](https://github.com/dnvriend/demo-akka-persistence-inmemory) I have created. It uses akka v2.4.6, Scala 2.11.8 and inmemory plugin v1.2.14.
