### ISSUE TITLE
Wrong resolver unresolved dependency: com.github.dnvriend#akka-persistence-inmemory_2.12;2.5.15.1: not found 

### ISSUE THREAD

**Issue by dgouyette** [dnvriend/akka-persistence-inmemory#61]
```
[warn]           +- com.technov:workshop-akka-persistence_2.12:1.0-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.github.dnvriend#akka-persistence-inmemory_2.12;2.5.15.1: not found
[error]     at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error]     at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]     at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]     at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[er
```

In Scala 2.12
It doesn't work with resolvers += Resolver.jcenterRepo
But it's works with resolvers += Resolver.bintrayRepo("dnvriend", "maven")

**Comment by vasily-kirichenko** [comment]
It did work for me a couple of days ago, see https://github.com/dnvriend/akka-persistence-inmemory/issues/60#issuecomment-432991923

**Comment by dgouyette** [comment]
Maybe you should update the documentation ;)

```
// the library is available in Bintray's JCenter
resolvers += Resolver.jcenterRepo
```

**Comment by vasily-kirichenko** [comment]
Me? I'm not a maintainer :)

**Comment by vasily-kirichenko** [comment]
However, https://github.com/dnvriend/akka-persistence-inmemory/pull/62 :)

**Comment by dnvriend** [comment]
There seems to be a problem at the side of Bintray. The artifacts are not being synced to JCentre.
